### ISSUE TITLE
How do "recommended" and "supported" differ?

### ISSUE THREAD

**Issue by ScottWales** [ACCESS-Hive/ACCESS-Hive#114]
The "recommended" support level also states that it is "supported at NCI" - how does this differ from the "supported" level? Are "supported" tools supported at other HPC sites?

**Comment by rbeucher** [comment]
We need to clarify the levels of support, I agree.

**Comment by ccarouge** [comment]
Let's have a go at some definitions:

"Supported" should be things the ACCESS-NRI is maintaining. 

"Recommended" are other things that are available to the community easily (so typically available at NCI) but not directly maintained by ACCESS-NRI. The ACCESS-NRI believes the recommended tools are of high quality and likely to be actively maintained.

"Community" is for anything that has been done or found by the community and that people want to share. But the quality hasn't been ascertained and there is no guarantee on the ongoing maintenance. Except that this definition currently breaks with the Data Catalogs for example. FLUXNET and OzFlux are listed under "Community" but they are of high quality and will keep on going.

**Comment by rbeucher** [comment]
There is limited support for non-NCI HPC though... I mean, happy to help but if we don't have control on the machine we can't really help much.

**Comment by ccarouge** [comment]
New definitions have been published by #143
