### ISSUE TITLE
External contribution workflow

### ISSUE THREAD

**Issue by ScottWales** [ACCESS-Hive/ACCESS-Hive#116]
When someone not in the organisation tries to do an ['edit directly on github'](https://access-hive.github.io/ACCESS-Hive/about/contribute/#edit-directly-on-github) change it won't give the option of committing directly to the main branch, instead it will make a fork for you under your own github account

**Comment by rbeucher** [comment]
Yes. That's the intended behavior. Should we clarify this maybe @ccarouge ?

**Comment by rbeucher** [comment]
We also need a way to get people to join the Github organisation. People can only be invited though. @ccarouge

**Comment by ccarouge** [comment]
Argh, I didn't want it to make a fork. I simply wanted it to make a branch and a PR.

**Comment by rbeucher** [comment]
Might be a good idea to invite the in-kinds to the organisation...

**Comment by ccarouge** [comment]
There is nothing about joining the GitHub organisation on ACCESS-Hive yet because we don't know how people should ask for an invite. If GitHub had a "request to join" option that would be a lot simpler!

**Comment by ccarouge** [comment]
Invitation sent to all the recipients of the message for feedback.
