### ISSUE TITLE
Training: review organisation from soft launch feedback

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-Hive/ACCESS-Hive#136]

**Comment by ccarouge** [comment]
- [ ] Move "Training resources from partners" to new page titled "Additional resources". Write NCI in full first time it is written.
- [ ] Review content of the Info box. (#72) Remove mention of specific teams.
- [ ] Change Technical training title. "How-to guides"?

**Comment by ccarouge** [comment]
This ticket contains and closes #135
